# DigitalOcean App Platform spec
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/
#
# Repo: https://github.com/Ruturaj2506/demo-auth
#
# HOW TO DEPLOY:
#   1. Go to https://cloud.digitalocean.com/apps → "Create App"
#   2. Connect GitHub → select Ruturaj2506/demo-auth → branch: main
#   3. DO auto-detects this file — click "Deploy"
#   5. App URL printed once build finishes (~3-5 min)

name: adaptiveauth

# ── Backend (FastAPI) ─────────────────────────────────────────────────────────
services:
  - name: api
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: Ruturaj2506/demo-auth
      branch: main
      deploy_on_push: true
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs   # cheapest tier (~$5/mo, free with student credits)
    health_check:
      http_path: /health
      initial_delay_seconds: 15
      period_seconds: 30
    envs:
      # Injected automatically by DO when you add a managed DB below
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${adaptiveauth-db.DATABASE_URL}

      # CHANGE THIS — generate a strong key: python -c "import secrets; print(secrets.token_hex(32))"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "REPLACE_WITH_YOUR_STRONG_SECRET_KEY"

      - key: ADAPTIVEAUTH_RISK_DEVICE_WEIGHT
        scope: RUN_TIME
        value: "0.21"
      - key: ADAPTIVEAUTH_RISK_LOCATION_WEIGHT
        scope: RUN_TIME
        value: "97.68"
      - key: ADAPTIVEAUTH_RISK_TIME_WEIGHT
        scope: RUN_TIME
        value: "0.02"
      - key: ADAPTIVEAUTH_RISK_VELOCITY_WEIGHT
        scope: RUN_TIME
        value: "2.08"
      - key: ADAPTIVEAUTH_RISK_BEHAVIOR_WEIGHT
        scope: RUN_TIME
        value: "0.01"

      # Optional — fill in if you want email alerts / OTP via email
      - key: ADAPTIVEAUTH_MAIL_USERNAME
        scope: RUN_TIME
        value: ""
      - key: ADAPTIVEAUTH_MAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ""
      - key: ADAPTIVEAUTH_MAIL_FROM
        scope: RUN_TIME
        value: ""
      - key: ADAPTIVEAUTH_MAIL_SERVER
        scope: RUN_TIME
        value: ""

# ── Managed PostgreSQL Database ───────────────────────────────────────────────
databases:
  - name: adaptiveauth-db
    engine: PG              # PostgreSQL 16
    version: "16"
    size: db-s-dev-database # smallest/free-eligible dev database
    num_nodes: 1
